---
- hosts: test_linux_server 
  tasks:
  - name: Execute a command using the shell module
    become: true
    become_user: root
    shell: helm install test-service /root/project/ansible/mytest --set service.type=NodePort

