---
- hosts: test_linux_server 
  tasks:
  - name: Execute a command using the shell module
    become: true
    become_user: root
    shell:  helm upgrade test-service /root/project/ansible/test --set service.type=NodePort

